[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    beegee-tokyo/DHT sensor library for ESPx @ ^1.19
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.2
    miguelbalboa/MFRC522 @ ^1.4.11